version: "3"

services:
  vue_project:
    container_name: client
    build: Web-Module-4
    depends_on:
      - asp_project
    logging: 
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    ports:
      - "5173:80"

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1453
      - MYSQL_USER=imysko
      - MYSQL_PASSWORD=1453
      - MYSQL_DATABASE=F1_cars
      - MYSQL_HOST=0.0.0.0
      - MYSQL_PORT=3306
    volumes:
      - ./.mysql-data/db:/var/lib/mysql

  asp_project:
    container_name: rest-server
    build: RESTApi
    depends_on:
      - mysql
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    volumes:
      - ./wwwroot/Media:/app/wwwroot/Media
    ports:
      - "7227:80"
