version: "3"

services:
  vue_project:
    build: Web-Module-4
    logging: 
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    ports:
      - "5173:80"
  asp_project:
    build: RESTApi
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    ports:
      - "7227:80"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1453
      - MYSQL_USER=imysko
      - MYSQL_PASSWORD=1453
      - MYSQL_DATABASE=F1_cars
      - MYSQL_HOST=0.0.0.0
      - MYSQL_PORT=3306
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
